# Generated by Django 5.0.2 on 2024-02-19 13:54

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
